# Generated by Django 4.0.6 on 2023-04-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('open', models.BooleanField()),
                ('closed', models.BooleanField()),
                ('high', models.CharField(max_length=30)),
                ('low', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
            ],
        ),
    ]
