# Generated by Django 4.0.6 on 2023-04-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
