# Generated by Django 4.0.6 on 2023-04-23 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acoes', '0003_alter_acao_closed_alter_acao_data_alter_acao_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acao',
            old_name='closed',
            new_name='close',
        ),
    ]
